name: venv
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.12.0
  - pip:
      - langchain_core==0.3.37
      - python-dotenv==1.0.1
      - streamlit==1.42.2
      - langchain_community==0.3.18
      - langserve==0.3.1
      - fastapi==0.115.8
      - uvicorn==0.34.0
      - sse_starlette==2.2.1
      - bs4==0.0.2
      - pypdf==5.3.0
      - chromadb==0.6.3
      - langchain-ollama==0.2.3
      - plotly==6.0.0
