name: data_privacy_law
channels:
  - defaults
dependencies:
  - pip=25.0
  - python=3.12.0
  - pip:
      - bs4==0.0.2
      - faiss-cpu==1.10.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.1
      - google-api-python-client==2.162.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.68.0
      - langchain==0.3.19
      - langchain-community==0.3.18
      - langchain-core==0.3.40
      - langchain-google-genai==2.0.10
      - langchain-text-splitters==0.3.6
      - langsmith==0.3.11
      - pandas==2.2.3
      - python-dotenv==1.0.1
      - plotly==6.0.0
      - pypdf==5.3.0
      - pylint==3.3.4
      - PyPDF2==3.0.1
      - streamlit==1.42.2
      - fastapi==0.115.8
